; hassio-bpx — asterisk.conf
; All mutable paths point to /data/ for HA backup compatibility (D-10)
[directories]
astetcdir    => /etc/asterisk
astmoddir    => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir     => /var/lib/asterisk
astkeydir    => /var/lib/asterisk
astdatadir   => /var/lib/asterisk
astagidir    => /var/lib/asterisk/agi-bin
astspooldir  => /data/voicemail
astrundir    => /var/run/asterisk
astlogdir    => /data/logs/asterisk
astsbindir   => /usr/sbin

[options]
transmit_silence = yes
nofork           = yes
