; hassio-bpx — voicemail.conf
; Voicemail spool location controlled by astspooldir in asterisk.conf
[general]
format      = wav
serveremail = pbx@hassio-bpx.local
attach      = yes
mailcmd     = /bin/true

#include "/data/asterisk/voicemail_mailboxes.conf"
