#!/usr/bin/with-contenv bashio
# ha-phone first-boot init
# Creates /data/ directory structure and /var/run/asterisk on every boot.
# /data/ dirs are idempotent (mkdir -p); AMI secret is generated on first boot.

bashio::log.info "ha-phone: running init script..."

# Always create /var/run/asterisk — tmpfs is re-mounted on each boot (Gotcha 8)
mkdir -p /var/run/asterisk

# First-boot: create persistent /data/ layout
if [ ! -f /data/.initialized ]; then
    bashio::log.info "First boot detected — creating /data/ directory structure..."

    mkdir -p /data/asterisk
    mkdir -p /data/db
    mkdir -p /data/voicemail/default
    mkdir -p /data/sounds/custom
    mkdir -p /data/logs/asterisk

    # Generate AMI secret (first boot only)
    if [ ! -f /data/asterisk/ami_secret ]; then
        bashio::log.info "Generating AMI secret..."
        python3 -c "import secrets; print(secrets.token_urlsafe(32))" > /data/asterisk/ami_secret
        chmod 600 /data/asterisk/ami_secret
        bashio::log.info "AMI secret written to /data/asterisk/ami_secret."
    fi

    # Generate self-signed TLS cert for the Phase 2 PJSIP test transport (D-06).
    # Dev-only, local-network-only per D-05 -- see 02-CONTEXT.md. Idempotent:
    # only generated once, same shape as the AMI secret above.
    mkdir -p /data/asterisk/tls
    if [ ! -f /data/asterisk/tls/asterisk.crt ]; then
        bashio::log.info "Generating self-signed TLS cert for PJSIP test transport..."
        openssl req -x509 -newkey rsa:2048 -nodes \
            -keyout /data/asterisk/tls/asterisk.key \
            -out /data/asterisk/tls/asterisk.crt \
            -days 3650 -subj "/CN=ha-phone-pjsip-test" \
            || bashio::log.warning "TLS cert generation failed -- transport-tls will not be written."
        [ -f /data/asterisk/tls/asterisk.key ] && chmod 600 /data/asterisk/tls/asterisk.key
        [ -f /data/asterisk/tls/asterisk.crt ] && bashio::log.info "TLS cert written to /data/asterisk/tls/asterisk.crt."
    fi

    # Placeholder generated confs (GAP-PJSIP-INCLUDE) — pjsip.conf and extensions.conf
    # #include these files, but the backend only generates them once an extension/trunk/
    # route is saved. On a fresh /data they are missing → Asterisk spams "#include does
    # not exist" and pbx_config declines to load. Create empty placeholders so the
    # #include chain parses cleanly on first boot. Idempotent + non-clobbering: only an
    # empty/missing file gets the comment header; a backend-written file is left untouched.
    # All targets live under /data/asterisk (CLAUDE.md: all mutable state under /data).
    for _conf in /data/asterisk/pjsip_extensions.conf \
                 /data/asterisk/pjsip_trunk.conf \
                 /data/asterisk/extensions_routing.conf \
                 /data/asterisk/voicemail_general.conf; do
        touch "/data/asterisk/$(basename "$_conf")"
        [ -s "$_conf" ] || echo "; placeholder — regenerated by backend on first save" > "$_conf"
    done
    bashio::log.info "ha-phone: ensured placeholder generated confs under /data/asterisk."

    touch /data/.initialized
fi

# Generate session secret (first boot only) — used by FastAPI SessionMiddleware (SEC-04)
SESSION_SECRET_FILE="/data/asterisk/session_secret"
if [ ! -f "$SESSION_SECRET_FILE" ]; then
    bashio::log.info "Generating session secret..."
    python3 -c "import secrets; print(secrets.token_urlsafe(32))" > "$SESSION_SECRET_FILE"
    chmod 600 "$SESSION_SECRET_FILE"
    bashio::log.info "Session secret written to /data/asterisk/session_secret."
fi

# Seed AdminUser on first run (idempotent — Python guards against re-seeding) (SEC-04, D-10)
ADMIN_PASSWORD=$(bashio::config 'admin_password' 2>/dev/null || echo "admin")
if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD="admin"
    bashio::log.warning "admin_password not set in options — using default 'admin'"
fi
PYTHONPATH=/app python3 -c "
import os, sys
os.environ['BPX_DATA_DIR'] = '/data'
from backend.database import init_db
from backend.models import AdminUser
from backend.auth import hash_password
from sqlmodel import Session, select
engine = init_db()
with Session(engine) as s:
    if not s.exec(select(AdminUser)).first():
        s.add(AdminUser(
            username='admin',
            hashed_password=hash_password(sys.argv[1]),
            must_change_password=True,
        ))
        s.commit()
        print('AdminUser seeded with must_change_password=True')
    else:
        print('AdminUser already exists — skipping seed')
" "$ADMIN_PASSWORD"

# Regenerate ALL Asterisk configs from the DB on EVERY boot — BEFORE Asterisk starts.
# Without this, a config file on /data is only rewritten when its object is created/
# edited via the web UI. So an add-on UPDATE that fixes a conf template never reaches
# existing installs (the old file lingers), and the broken live-reload meant edits did
# not apply until a manual restart anyway. Regenerating from the DB here makes the
# running config always match the DB + the current templates, and is self-healing for
# stale/partial conf files. Non-fatal: a failure logs a warning and boot continues.
bashio::log.info "ha-phone: regenerating Asterisk configs from DB..."
PYTHONPATH=/app python3 -c "
import os
os.environ['BPX_DATA_DIR'] = '/data'
from sqlmodel import Session, select
from backend.database import init_db
from backend.models import Trunk
from backend.regeneration import run_regeneration_steps, skipped_regeneration
from backend.routers.extensions import _regenerate_extensions_conf, _regenerate_voicemail_conf
from backend.routers.time_conditions import _regenerate_routing_conf
from backend.routers.trunk import _regenerate_trunk_conf
from backend.routers.outbound_rules import seed_default_outbound_rules
from backend.routers.settings import regenerate_mail_configs
engine = init_db()
with Session(engine) as s:
    try:
        seeded = seed_default_outbound_rules(s)
        if seeded:
            print('default outbound rules seeded')
    except Exception as exc:
        print(f'default outbound rule seed failed: {type(exc).__name__}: {exc}')
    trunk = s.exec(select(Trunk)).first()
    summary = run_regeneration_steps(
        'boot.init',
        [
            ('extensions', lambda: _regenerate_extensions_conf(s)),
            ('voicemail', lambda: _regenerate_voicemail_conf(s)),
            ('routing', lambda: _regenerate_routing_conf(s)),
            ('mail', lambda: regenerate_mail_configs(s)),
            (
                'trunk',
                lambda trunk=trunk: _regenerate_trunk_conf(trunk)
                if trunk is not None
                else skipped_regeneration('Kein Trunk konfiguriert'),
            ),
        ],
    )
failed = [step for step in summary['steps'] if not step.get('ok')]
if failed:
    print('config regeneration completed with failures')
    for step in failed:
        print(f\"- {step['name']}: {step['message']}\")
else:
    print('configs regenerated from DB')
" || bashio::log.warning "ha-phone: config regeneration failed — Asterisk uses existing /data confs."

# Set permissions — Asterisk runs as root in this container
chown -R root:root /data/voicemail /data/logs /data/asterisk
chmod -R 755 /data/voicemail /data/logs /data/asterisk

# Update manager.conf secret from generated file (every boot — manager.conf is in image)
if [ -f /data/asterisk/ami_secret ] && [ -f /etc/asterisk/manager.conf ]; then
    AMI_SECRET=$(cat /data/asterisk/ami_secret)
    sed -i "s/^secret[[:space:]]*=.*/secret = ${AMI_SECRET}/" /etc/asterisk/manager.conf
    # Verify replacement worked
    if grep -q "^secret.*=.*changeme" /etc/asterisk/manager.conf 2>/dev/null; then
        bashio::log.warning "AMI secret sed FAILED — manager.conf still has placeholder! Forcing replacement..."
        sed -i "/^\[bpx-admin\]/,/^secret/{s/^secret.*/secret = ${AMI_SECRET}/}" /etc/asterisk/manager.conf
    fi
    AMI_SECRET_LEN=${#AMI_SECRET}
    bashio::log.info "manager.conf AMI secret updated (length=${AMI_SECRET_LEN})."
fi

# ── externip auto-detect — D-02 ───────────────────────────────────────────────
# Detect external IP for pjsip NAT config. IPv6 preferred (DG CGNAT gives
# 100.64.x.x for IPv4 which is not routable from the internet).
# Writes /data/asterisk/pjsip_local.conf — included by /etc/asterisk/pjsip.conf.
# On failure: writes a comment-only placeholder so the #include does not error.

bashio::log.info "ha-phone: detecting external IP address for pjsip NAT config..."

PJSIP_LOCAL="/data/asterisk/pjsip_local.conf"

# Prefer IPv6 — DG CGNAT (100.64.x.x) makes IPv4 useless for external SIP Contact
EXTERNAL_IP=$(ip -6 addr show scope global | grep -oP '(?<=inet6 )[\da-f:]+(?=/)' \
    | grep -v '^fc\|^fd\|^fe80' | head -1 || true)

if [ -z "$EXTERNAL_IP" ]; then
    # IPv4 fallback — only useful if behind full-cone NAT (not DG CGNAT)
    EXTERNAL_IP=$(curl -s --max-time 3 https://api4.ipify.org 2>/dev/null || true)
    # Discard CGNAT 100.64.0.0/10 range
    if echo "$EXTERNAL_IP" | grep -qE '^100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.' 2>/dev/null; then
        EXTERNAL_IP=""
    fi
fi

if [ -n "$EXTERNAL_IP" ]; then
    bashio::log.info "ha-phone: external IP detected: ${EXTERNAL_IP}"
    cat > "$PJSIP_LOCAL" <<HEREDOC
; Auto-generated by cont-init.d/10-asterisk-init.sh — do not edit manually
; Extends transport-udp defined in /etc/asterisk/pjsip.conf

[transport-udp](+)
external_signaling_address = ${EXTERNAL_IP}
external_media_address     = ${EXTERNAL_IP}
local_net                  = 192.168.0.0/16
local_net                  = 10.0.0.0/8
local_net                  = 172.16.0.0/12
; Tailscale/WireGuard VPN — treat remote softphones on the VPN as local so RTP
; goes straight over the tunnel (no external_media rewrite → clean audio).
local_net                  = 100.64.0.0/10
local_net                  = fd7a:115c:a1e0::/48
HEREDOC
    bashio::log.info "ha-phone: wrote pjsip_local.conf with external IP."
else
    bashio::log.warning "ha-phone: could not detect external IP — pjsip_local.conf not written; Asterisk starts in LAN-only mode."
    # Write comment-only placeholder so pjsip.conf #include does not fail on missing file
    cat > "$PJSIP_LOCAL" <<'HEREDOC'
; Auto-generated by cont-init.d/10-asterisk-init.sh — do not edit manually
; External IP detection failed — Asterisk running in LAN-only mode
; No externip configured. Restart the add-on to retry detection.
HEREDOC
fi

# ── [transport-tls] -- D-06 ────────────────────────────────────────────
if [ -f /data/asterisk/tls/asterisk.crt ] && [ -f /data/asterisk/tls/asterisk.key ]; then
    if ! grep -q '^\[transport-tls\]' "$PJSIP_LOCAL" 2>/dev/null; then
        cat >> "$PJSIP_LOCAL" <<HEREDOC

[transport-tls]
type       = transport
protocol   = tls
bind       = 0.0.0.0:5061
cert_file  = /data/asterisk/tls/asterisk.crt
priv_key_file = /data/asterisk/tls/asterisk.key
method     = tlsv1_2
HEREDOC
        bashio::log.info "ha-phone: appended [transport-tls] to pjsip_local.conf."
    fi
else
    bashio::log.warning "ha-phone: TLS cert missing -- [transport-tls] not written, TLS test extension unreachable."
fi

bashio::log.info "ha-phone: init script done."
